# controllers/pure_pursuit.yaml
controller_plugins:
  - FollowPath
controller_plugins_dict:
  FollowPath:
    plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
    desired_linear_vel: 0.5
    lookahead_dist: 0.6
    min_lookahead_dist: 0.3