planner_plugins_dict:
  planner_plugins: ['ThetaStar']
  ThetaStar:
    plugin: 'nav2_theta_star_planner/ThetaStarPlanner'
    use_final_approach_orientation: false
    allow_unknown: true
    tolerance: 0.5
    how_many_corners: 8
    w_euc_cost: 1.0
    w_traversal_cost: 2.0