bt_navigator:
  ros__parameters:
    default_nav_to_pose_bt_xml: "$(find-pkg-share arena_simulation_setup)/configs/nav2/interplanners/empty/interplanner_behaviour.xml"
    default_nav_through_poses_bt_xml: "$(find-pkg-share arena_simulation_setup)/configs/nav2/interplanners/empty/interplanner_behaviour.xml"
    plugin_lib_names:
      - "nav2_compute_path_to_pose_action_bt_node" # minimal configuration for plugin_lib_names
                                                   # has no effect since empty behavior tree is used which does not use any plugins but is used to avoid error

      
