planner_plugins_dict:
  planner_plugins: ['GridBased']
  GridBased:
    plugin: 'nav2_smac_planner/SmacPlannerLattice'
    allow_unknown: true
    tolerance: 0.25
    max_iterations: 1000000
    max_on_approach_iterations: 1000
    max_planning_time: 5.0
    analytic_expansion_ratio: 3.5
    analytic_expansion_max_length: 3.0
    analytic_expansion_max_cost: 200.0
    analytic_expansion_max_cost_override: false
    reverse_penalty: 2.0
    change_penalty: 0.05
    non_straight_penalty: 1.05
    cost_penalty: 2.0
    rotation_penalty: 5.0
    retrospective_penalty: 0.015
    lattice_filepath: ""
    lookup_table_size: 20.0
    cache_obstacle_heuristic: false
    allow_reverse_expansion: false
    smooth_path: true
    smoother:
      max_iterations: 1000
      w_smooth: 0.3
      w_data: 0.2
      tolerance: 1.0e-10
      do_refinement: true
      refinement_num: 2