#https://github.com/inomuh/agv/blob/7c5e97311a77bd878fdaeba2b263bd6aa054db71/agv_navigation/params/agv_local.yaml
update_frequency: 5.0
publish_frequency: 5.0

static_map: true
rolling_window: true

width: 4.0
height: 4.0
resolution: 0.05


observation_sources: scan